testing refresh of d-acts import
ufbmi/OMRSE pull request #185
Opened 2022-06-02 02:22 UTC by wdduncan

- replace http://purl.obolibrary.org/obo/iao/d-acts/release/2020-10-14/d-acts.owl with http://purl.obolibrary.org/obo/iao/d-acts.owl
- add new d-acts

2022-06-02 03:18 UTC, wdduncan commented
@hoganwr @dillerm @CDowland 

I created this PR by forking the OMRSE repo. Here is a summary of what is going on when using ODK to refresh the d-acts import.

When you execute`make refresh-d-acts` on your machine, the relevant part of the `makefile` that runs is this:
```
$(IMPORTDIR)/d-acts_import.owl: $(MIRRORDIR)/d-acts.owl $(IMPORTDIR)/d-acts_terms_combined.txt
        if [ $(IMP) = true ]; then $(ROBOT) merge -i $< \
                query --update ../sparql/preprocess-module.ru --update ../sparql/inject-subset-declaration.ru --update ../sparql/postprocess-module.ru \
                annotate --ontology-iri $(ONTBASE)/$@ $(ANNOTATE_ONTOLOGY_VERSION) --output $@.tmp.owl && mv $@.tmp.owl $@; fi
```
Unpacking this gave me a headache, but here is my crude summary:
- The goal/dependency `$(MIRRORDIR)/d-acts.owl` will create a `mirror` directory and download `d-acts.owl` into it. The `mirror` is only present on your local machine, and not on the remote repo. This is b/c in the `omrse/.gitignore` file the `src/ontology/mirror` is specified as being ignored.
- The rest of the make command calls `robot` to do a bunch of processing on the `mirror/d-act.owl` file in order to create the `imports/d-act_import.owl` file.

The first time I ran `make refresh-d-acts` nothing changed in regards to the number of definitions for `aggregate of organizations`. I found this odd, but then noticed that command for creating the d-acts mirror was tied to a specific version of the ontology:
```
mirror-d-acts: | $(TMPDIR)
     if [ $(MIR) = true ] && [ $(IMP) = true ]; then $(ROBOT) 
     convert -I http://purl.obolibrary.org/obo/iao/d-acts/release/2020-10-14/d-acts.owl 
    -o $@.tmp.owl && mv $@.tmp.owl $(TMPDIR)/$@.owl; fi
```
Notice the `release/2020-10-14/d-acts.owl` part of the IRI. 

I don't know if locking on to this specific release was by design, but I changed the Makefile to pull the most current version of d-acts. See line `454` in the  Makefile diff.

Now, after running `make refresh-d-acts`, a new `d-acts_import.owl` file was created. Because `d-acts_import.owl` is saved as rdf/xml, the order in which rdf/xml is written is not consistent. This can (and does) create a bunch of spurious diffs (I know ... annoying). But, if go to lines `8583-8651` of the `d-acts_import.owl` diff, you will indeed see that two definitions have been replaced by a single definition. Here is a screenshot.

<img width="1239" alt="image" src="https://user-images.githubusercontent.com/3186638/171543799-d48d3d91-6dfe-4b72-b53d-1b80715633b0.png">

So did this fix the problem? ... **NO!** If you open the `omrse-edit.owl` file you see that `aggregate of organizations` still has two definitions (grrr...).

<img width="957" alt="image" src="https://user-images.githubusercontent.com/3186638/171544073-b6ac7db4-56c4-4002-b1a3-c5e4848436c4.png">

The reason for this is b/c `omrse-edit.owl` a definition `aggregate of organizations` has been created within `omrse-edit.owl`. To see this, select the option to `Show only the active ontology` in Protege:

<img width="567" alt="image" src="https://user-images.githubusercontent.com/3186638/171544851-2403299c-79da-4a8f-8ae2-f7ad6f7d6b5c.png">

Now you see the **single** definition that has been created within the `omrse-edit.owl` file:

<img width="1118" alt="image" src="https://user-images.githubusercontent.com/3186638/171545000-6d27b32f-4809-4016-b4ba-72b9b0771005.png">

However, since `omrse-edit.owl` is importing `imports/d-acts_imports.owl` and `imports/d-acts_imports.owl` has a different definition for `aggregate of organizations`, two definitions will be present when you view `omrse-edit.owl` using the `Show the imports closure of the active ontology` option in Protege (which is the viewing option I most commonly use):

<img width="550" alt="image" src="https://user-images.githubusercontent.com/3186638/171545479-122b6c27-78fc-41ca-a250-f0d3ac1ee9cd.png">

So, at this point, it is unclear what is the source of truth for the definition of `aggregate of organizations`. Is it one in the most recent release of `d-acts` or the one `omrse`?

2022-06-02 11:40 UTC, mbrochhausen commented
I am not sure whether this is a d-acts issue. If so , please let me know and I fix it asap.

Best,
Mathias 

Sent from my iPhone

> On Jun 1, 2022, at 10:18 PM, Bill Duncan ***@***.***> wrote:
> 
> ﻿
> @hoganwr @dillerm @CDowland
> 
> I created this PR by forking the OMRSE repo. Here is a summary of what is going on when using ODK to refresh the d-acts import.
> 
> When you executemake refresh-d-acts on your machine, the relevant part of the makefile that runs is this:
> 
> $(IMPORTDIR)/d-acts_import.owl: $(MIRRORDIR)/d-acts.owl $(IMPORTDIR)/d-acts_terms_combined.txt
>         if [ $(IMP) = true ]; then $(ROBOT) merge -i $< \
>                 query --update ../sparql/preprocess-module.ru --update ../sparql/inject-subset-declaration.ru --update ../sparql/postprocess-module.ru \
>                 annotate --ontology-iri $(ONTBASE)/$@ $(ANNOTATE_ONTOLOGY_VERSION) --output ***@***.*** && mv ***@***.*** $@; fi
> Unpacking this gave me a headache, but here is my crude summary:
> 
> The goal/dependency $(MIRRORDIR)/d-acts.owl will create a mirror directory and download d-acts.owl into it. The mirror is only present on your local machine, and not on the remote repo. This is b/c in the omrse/.gitignore file the src/ontology/mirror is specified as being ignored.
> The rest of the make command calls robot to do a bunch of processing on the mirror/d-act.owl file in order to create the imports/d-act_import.owl file.
> The first time I ran make refresh-d-acts nothing changed in regards to the number of definitions for aggregate of organizations. I found this odd, but then noticed that command for creating the d-acts mirror was tied to a specific version of the ontology:
> 
> mirror-d-acts: | $(TMPDIR)
>      if [ $(MIR) = true ] && [ $(IMP) = true ]; then $(ROBOT) 
>      convert -I http://purl.obolibrary.org/obo/iao/d-acts/release/2020-10-14/d-acts.owl 
>     -o ***@***.*** && mv ***@***.*** ***@***.***; fi
> Notice the release/2020-10-14/d-acts.owl part of the IRI.
> 
> I don't know if locking on to this specific release was by design, but I changed the Makefile to pull the most current version of d-acts. See line 454 in the Makefile diff.
> 
> Now, after running make refresh-d-acts, a new d-acts_import.owl file was created. Because d-acts_import.owl is saved as rdf/xml, the order in which rdf/xml is written is not consistent. This can (and does) create a bunch of spurious diffs (I know ... annoying). But, if go to lines 8583-8651 of the d-acts_import.owl diff, you will indeed see that two definitions have been replaced by a single definition. Here is a screenshot.
> 
> 
> 
> So did this fix the problem? ... NO! If you open the omrse-edit.owl file you see that aggregate of organizations still has two definitions (grrr...).
> 
> 
> 
> The reason for this is b/c omrse-edit.owl a definition aggregate of organizations has been created within omrse-edit.owl. To see this, select the option to Show only the active ontology in Protege:
> 
> 
> 
> Now you see the single definition that has been created within the omrse-edit.owl file:
> 
> 
> 
> However, since omrse-edit.owl is importing imports/d-acts_imports.owl and imports/d-acts_imports.owl has a different definition for aggregate of organizations, two definitions will be present when you view omrse-edit.owl using the Show the imports closure of the active ontology option in Protege (which is the viewing option I most commonly use):
> 
> 
> 
> So, at this point, it is unclear what is the source of truth for the definition of aggregate of organizations. Is it one in the most recent release of d-acts or the one omrse?
> 
> —
> Reply to this email directly, view it on GitHub, or unsubscribe.
> You are receiving this because you are subscribed to this thread.

2022-06-02 11:48 UTC, matentzn requested changes

2022-06-02 11:48 UTC, matentzn commented on src/ontology/Makefile
> -	if [ $(MIR) = true ] && [ $(IMP) = true ]; then $(ROBOT) convert -I http://purl.obolibrary.org/obo/iao/d-acts/release/2020-10-14/d-acts.owl -o $@.tmp.owl && mv $@.tmp.owl $(TMPDIR)/$@.owl; fi
Never change the Makefile directly, ODK will overwrite during the next ODK update. YOu should:

Change this line:
https://github.com/ufbmi/OMRSE/blob/master/src/ontology/omrse-odk.yaml#L53 according to you suggestion here.

then run:

```
docker pull obolibrary/odkfull #too make sure you use the latest odk
sh run.sh make update_repo #run twice, the first one may error.
```

2022-06-02 11:51 UTC, hoganwr commented
Bill, thank you!!!  It is an OMRSE class, so the OMRSE definition takes precedence.  If it needs editing, happy to do it, but it needs to be sourced from OMRSE.

Also, I think tying imports to specific versions of ontologies is double-edged sword.  You have finer-grained control over your dependencies (i.e., external ontologies), but then you have to be conscientious about reviewing new versions of those ontologies, and migrating to those versions (and not just flailing about wondering why they're causing issues LOL).  

How do other ODK-based ontologies handle sourcing versions of imported ontologies?

2022-06-02 12:02 UTC, matentzn commented
@hoganwr we do not - in all OBO ontologies we work with, we try to use the latest version at all times! This makes sure that OBO ontologies are always mutually intercompatible, and issues are fixed as they arise! I would _not_ recommend using version IRIs with your imports!

2022-06-02 12:55 UTC, mbrochhausen commented
I agree. The me previous email.

Sent from my iPhone

> On Jun 2, 2022, at 7:03 AM, Nico Matentzoglu ***@***.***> wrote:
> 
> ﻿
> @hoganwr we do not - in all OBO ontologies we work with, we try to use the latest version at all times! This makes sure that OBO ontologies are always mutually intercompatible, and issues are fixed as they arise! I would not recommend using version IRIs with your imports!
> 
> —
> Reply to this email directly, view it on GitHub, or unsubscribe.
> You are receiving this because you commented.

2022-06-02 15:54 UTC, wdduncan commented on src/ontology/Makefile
> -	if [ $(MIR) = true ] && [ $(IMP) = true ]; then $(ROBOT) convert -I http://purl.obolibrary.org/obo/iao/d-acts/release/2020-10-14/d-acts.owl -o $@.tmp.owl && mv $@.tmp.owl $(TMPDIR)/$@.owl; fi
Thanks. I forgot about the `yaml` file!

2022-06-02 15:58 UTC, wdduncan commented
I don't have permissions to merge. But, this should be ready now.

2022-06-02 16:00 UTC, matentzn approved these changes

2022-06-02 18:22 UTC, hoganwr commented
THanks for that wisdom!  I'm currently running checks, then will merge.  And yes Bill I'll give you permissions as well.

2022-06-02 18:23 UTC, merged

2022-10-11 09:01 UTC, mbrochhausen commented
Hi,

I agree that the definition should be OMRSE. I also agree that importing an older version is only a second best solution. I remember that this had to do with disagreements among d-acts developers, but those issues are no longer pertinent.

Please let me know what I should change in d-acts and I’ll do it asap.

Best,
Mathias 

Sent from my iPhone

> On Jun 2, 2022, at 6:51 AM, Bill Hogan ***@***.***> wrote:
> 
> ﻿
> Bill, thank you!!! It is an OMRSE class, so the OMRSE definition takes precedence. If it needs editing, happy to do it, but it needs to be sourced from OMRSE.
> 
> Also, I think tying imports to specific versions of ontologies is double-edged sword. You have finer-grained control over your dependencies (i.e., external ontologies), but then you have to be conscientious about reviewing new versions of those ontologies, and migrating to those versions (and not just flailing about wondering why they're causing issues LOL).
> 
> How do other ODK-based ontologies handle sourcing versions of imported ontologies?
> 
> —
> Reply to this email directly, view it on GitHub, or unsubscribe.
> You are receiving this because you commented.